
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 0035119
 */
public class App extends javax.swing.JFrame {

    
    ArrayList<Pessoa> listaDePessoas;
    File listaPessoasArquivo = new File("Pessoas.bin");
    int registroAtual;
    
    /**
     * Creates new form App
     */
    public App() {
        registroAtual = -1;
        listaDePessoas = new ArrayList<Pessoa>();
        initComponents();
        if ( listaPessoasArquivo.exists() && 
             JOptionPane.showConfirmDialog(this,
                                     "Há cadastros prévios, deseja carragar?",
                                      "Recarregar?", 
                                  JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ) {
            jbABRIRMouseClicked(null);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jbADICIONAR = new javax.swing.JButton();
        tfContagem = new javax.swing.JTextField();
        jbVOLTAR = new javax.swing.JButton();
        jbAvancar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jbABRIR = new javax.swing.JButton();
        jbSALVAR = new javax.swing.JButton();
        jbREMOVER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Idade");

        jLabel3.setText("Endereço");

        jbADICIONAR.setText("ADICIONAR");
        jbADICIONAR.setRequestFocusEnabled(false);
        jbADICIONAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbADICIONARMouseClicked(evt);
            }
        });
        jbADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbADICIONARActionPerformed(evt);
            }
        });

        tfContagem.setEditable(false);
        tfContagem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfContagem.setText("0");
        tfContagem.setFocusable(false);
        tfContagem.setRequestFocusEnabled(false);

        jbVOLTAR.setText("VOLTAR");
        jbVOLTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVOLTARMouseClicked(evt);
            }
        });
        jbVOLTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVOLTARActionPerformed(evt);
            }
        });

        jbAvancar.setText("AVANÇAR");
        jbAvancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAvancarMouseClicked(evt);
            }
        });

        jLabel6.setText("<html>Este exemplo demonstra um formulário que armazena instâncias de Pessoa com base nos valores fornecidos através dos campos Nome, Idade e Endereço. Cada resgistro de uma pessoa é armazenado em um ArrayList de objetos Pessoa. Por fim, é possível navegar pelos registros armazenados na lista e remover o regstro atual. Os botões de \"ABRIR ARQUIVO\" e \"SALVAR EM ARQUIVO\" carregam ou salvam os dados do ArrayList em um arquivo binário Pessoas.bin, que pode ser encontrado na pasta raiz do projeto. O software também oferece a opção de carregar cadastros já registrados em arquivo no momento da inicialização.</html>");

        jbABRIR.setText("ABRIR ARQUIVO");
        jbABRIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbABRIRMouseClicked(evt);
            }
        });

        jbSALVAR.setText("SALVAR EM ARQUIVO");
        jbSALVAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSALVARMouseClicked(evt);
            }
        });

        jbREMOVER.setText("REMOVER");
        jbREMOVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbREMOVERMouseClicked(evt);
            }
        });
        jbREMOVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbREMOVERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfEndereco)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbADICIONAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbREMOVER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbVOLTAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAvancar)
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfContagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbABRIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSALVAR)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tfContagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbADICIONAR)
                    .addComponent(jbVOLTAR)
                    .addComponent(jbAvancar)
                    .addComponent(jbREMOVER))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbABRIR)
                    .addComponent(jbSALVAR))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAvancarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAvancarMouseClicked
        if ( registroAtual < listaDePessoas.size() - 1  ) {
            registroAtual++;
            tfNome.setText(listaDePessoas.get(registroAtual).getNome());
            tfIdade.setText(Integer.toString(listaDePessoas.get(registroAtual).getIdade()));
            tfEndereco.setText(listaDePessoas.get(registroAtual).getEndereco());
            tfContagem.setText(Integer.toString(registroAtual + 1));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAvancarMouseClicked

    private void jbVOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVOLTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVOLTARActionPerformed

    private void jbVOLTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVOLTARMouseClicked
        if ( registroAtual > 0  ) {
            registroAtual--;
            tfNome.setText(listaDePessoas.get(registroAtual).getNome());
            tfIdade.setText(Integer.toString(listaDePessoas.get(registroAtual).getIdade()));
            tfEndereco.setText(listaDePessoas.get(registroAtual).getEndereco());
            tfContagem.setText(Integer.toString(registroAtual + 1));
        }
    }//GEN-LAST:event_jbVOLTARMouseClicked

    private void jbREMOVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbREMOVERMouseClicked
        listaDePessoas.remove(registroAtual);
        jbVOLTARMouseClicked(null);
    }//GEN-LAST:event_jbREMOVERMouseClicked

    private void jbADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbADICIONARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbADICIONARActionPerformed

    private void jbADICIONARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbADICIONARMouseClicked

        Pessoa p = new Pessoa(tfNome.getText(),
            Integer.parseInt(tfIdade.getText()),
            tfEndereco.getText());
        listaDePessoas.add(p);
        registroAtual = listaDePessoas.size() - 1;
        tfContagem.setText(Integer.toString(registroAtual + 1));
        System.out.println(listaDePessoas);

    }//GEN-LAST:event_jbADICIONARMouseClicked

    private void jbSALVARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSALVARMouseClicked
        FileOutputStream fos;
        try {
            fos = new FileOutputStream(listaPessoasArquivo); //https://docs.oracle.com/javase/8/docs/api/java/io/FileOutputStream.html
            ObjectOutputStream oos = new ObjectOutputStream(fos); // https://docs.oracle.com/javase/8/docs/api/java/io/ObjectOutputStream.html
            oos.writeObject(listaDePessoas);
            oos.close();
            fos.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbSALVARMouseClicked

    private void jbABRIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbABRIRMouseClicked
        FileInputStream fis;
        try {
            fis = new FileInputStream(listaPessoasArquivo);
            ObjectInputStream ois = new ObjectInputStream(fis);
            listaDePessoas = (ArrayList<Pessoa>) ois.readObject();
            ois.close();
            fis.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Arquivo Pessoas.bin não encontrado");
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this,"Erro na leitura do arquivo Pessoas.bin");
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
        registroAtual = 0;
        tfNome.setText(listaDePessoas.get(registroAtual).getNome());
        tfIdade.setText(Integer.toString(listaDePessoas.get(registroAtual).getIdade()));
        tfEndereco.setText(listaDePessoas.get(registroAtual).getEndereco());
        tfContagem.setText(Integer.toString(registroAtual + 1));

        // TODO add your handling code here:
    }//GEN-LAST:event_jbABRIRMouseClicked

    private void jbREMOVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbREMOVERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbREMOVERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbABRIR;
    private javax.swing.JButton jbADICIONAR;
    private javax.swing.JButton jbAvancar;
    private javax.swing.JButton jbREMOVER;
    private javax.swing.JButton jbSALVAR;
    private javax.swing.JButton jbVOLTAR;
    private javax.swing.JTextField tfContagem;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
