/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import br.com.forasteros.estoquefarmashow.Usuario;
import static br.com.forasteros.estoquefarmashow.Usuario.carregarDados;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author super
 */
public class TelaCadUser extends javax.swing.JFrame {
    private List<Usuario> usuarios; // Declaração da lista de usuários
       
    /**
     * Creates new form TelaCadUser
     */
    public TelaCadUser() {
        initComponents();
        ArrayList<Usuario> usuarios = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tcuEmail = new javax.swing.JTextField();
        tcuUser = new javax.swing.JTextField();
        tcuPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        tcuNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tcuSobrenome = new javax.swing.JTextField();
        tcuCadastra = new javax.swing.JButton();
        tcuCPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tcuDeleta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcuMostra = new javax.swing.JTable();
        tcuLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("e-mail");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("usuário");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nome");

        tcuEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuEmailActionPerformed(evt);
            }
        });

        tcuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuUserActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Sobrneome");

        tcuNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuNomeActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Senha");

        tcuSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuSobrenomeActionPerformed(evt);
            }
        });

        tcuCadastra.setText("Cadastrar");
        tcuCadastra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcuCadastraMouseClicked(evt);
            }
        });
        tcuCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuCadastraActionPerformed(evt);
            }
        });

        try {
            tcuCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("CPF");

        tcuDeleta.setText("Deletar");
        tcuDeleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuDeletaActionPerformed(evt);
            }
        });

        tcuMostra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cadastro", "Usuário", "Nome", "Sobrenome", "E-mail"
            }
        ));
        tcuMostra.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tcuMostraAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tcuMostra);

        tcuLista.setText("Listar");
        tcuLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcuListaMouseClicked(evt);
            }
        });
        tcuLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcuListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tcuCadastra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcuDeleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tcuLista))
                    .addComponent(tcuCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tcuUser)
                    .addComponent(tcuEmail)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcuSobrenome)
                    .addComponent(tcuNome)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcuPass)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(tcuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcuCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcuSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tcuPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcuCadastra)
                            .addComponent(tcuDeleta)
                            .addComponent(tcuLista))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tcuEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuEmailActionPerformed

    private void tcuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuUserActionPerformed

    private void tcuNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuNomeActionPerformed

    private void tcuSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuSobrenomeActionPerformed

    private void tcuCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuCadastraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuCadastraActionPerformed

    private void tcuCadastraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcuCadastraMouseClicked
    String nome = tcuNome.getText();
    String sobrenome = tcuSobrenome.getText();
    String email = tcuEmail.getText();
    String usuario = tcuUser.getText();
    String senha = new String(tcuPass.getPassword());
    String CPF = tcuCPF.getText();

    Usuario usuarioObj = new Usuario();
    usuarioObj.setNome(nome);
    usuarioObj.setSobrenome(sobrenome);
    usuarioObj.setEmail(email);
    usuarioObj.setUsuario(usuario);
    usuarioObj.setSenha(senha);
    usuarioObj.setCpf(CPF);

    usuarios.add(usuarioObj); // Adicione o usuário ao ArrayList

    usuarioObj.salvarDados(usuarios);
    
    }//GEN-LAST:event_tcuCadastraMouseClicked

    private void tcuMostraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tcuMostraAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuMostraAncestorAdded

    private void tcuListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcuListaMouseClicked
        DefaultTableModel model = (DefaultTableModel) tcuMostra.getModel();
        model.setRowCount(0);

        usuarios = (List<Usuario>) carregarDados();

        for (Usuario usuario : usuarios) {
            Object[] row = {usuario.getCadastro(), usuario.getUsuario(), usuario.getNome(), usuario.getSobrenome(), usuario.getEmail()};
            model.addRow(row);
        }
    }//GEN-LAST:event_tcuListaMouseClicked

    private void tcuListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcuListaActionPerformed

    private void tcuDeletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcuDeletaActionPerformed

        // Verificar se há elementos na lista
    if (!listaDePessoas.isEmpty()) {
        // Remover o objeto atual da lista
        listaDePessoas.remove(registroAtual);
        
        // Atualizar o valor do registroAtual
        if (registroAtual >= listaDePessoas.size()) {
            registroAtual = listaDePessoas.size() - 1;
        }
        
        // Atualizar os campos com o objeto atual, se houver
        if (registroAtual >= 0) {
            Pessoa pessoaAtual = listaDePessoas.get(registroAtual);
            tfNome.setText(pessoaAtual.getNome());
            tfIdade.setText(Integer.toString(pessoaAtual.getIdade()));
            tfEndereco.setText(pessoaAtual.getEndereco());
        } else {
            // Limpar os campos se a lista estiver vazia
            tfNome.setText("");
            tfIdade.setText("");
            tfEndereco.setText("");
        }
        
        // Atualizar a exibição da contagem e quantidade de registros
        tfContagem.setText(Integer.toString(registroAtual + 1));
        JOptionPane.showMessageDialog(this, "Registro removido com sucesso.");
    } else {
        JOptionPane.showMessageDialog(this, "Não há registros para remover.");
    }
    }//GEN-LAST:event_tcuDeletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField tcuCPF;
    private javax.swing.JButton tcuCadastra;
    private javax.swing.JButton tcuDeleta;
    private javax.swing.JTextField tcuEmail;
    private javax.swing.JButton tcuLista;
    private javax.swing.JTable tcuMostra;
    private javax.swing.JTextField tcuNome;
    private javax.swing.JPasswordField tcuPass;
    private javax.swing.JTextField tcuSobrenome;
    private javax.swing.JTextField tcuUser;
    // End of variables declaration//GEN-END:variables
}
