/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author super
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        botArq = new javax.swing.JMenu();
        botSair = new javax.swing.JMenuItem();
        botUser = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        botForne = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        botProd = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        botSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - Farma Show");

        botArq.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\OneDrive\\Documentos\\1FACULDADE\\Prog1\\FarmShow\\EstoqueFarmaShow\\src\\main\\java\\imagens\\page.png")); // NOI18N
        botArq.setText("Arquivo");

        botSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\OneDrive\\Documentos\\1FACULDADE\\Prog1\\FarmShow\\EstoqueFarmaShow\\src\\main\\java\\imagens\\door_out.png")); // NOI18N
        botSair.setText("Sair");
        botSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botSairMousePressed(evt);
            }
        });
        botArq.add(botSair);

        jMenuBar1.add(botArq);

        botUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\OneDrive\\Documentos\\1FACULDADE\\Prog1\\FarmShow\\EstoqueFarmaShow\\src\\main\\java\\imagens\\user.png")); // NOI18N
        botUser.setText("Usuários");

        jMenuItem2.setText("Gerenciar");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        botUser.add(jMenuItem2);

        jMenuBar1.add(botUser);

        botForne.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\OneDrive\\Documentos\\1FACULDADE\\Prog1\\FarmShow\\EstoqueFarmaShow\\src\\main\\java\\imagens\\group.png")); // NOI18N
        botForne.setText("Fornecedores");

        jMenuItem6.setText("Gerenciar");
        botForne.add(jMenuItem6);

        jMenuItem7.setText("Listar");
        botForne.add(jMenuItem7);

        jMenuBar1.add(botForne);

        botProd.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\OneDrive\\Documentos\\1FACULDADE\\Prog1\\FarmShow\\EstoqueFarmaShow\\src\\main\\java\\imagens\\package.png")); // NOI18N
        botProd.setText("Produtos");

        jMenuItem10.setText("Gerenciar");
        botProd.add(jMenuItem10);

        jMenuItem11.setText("Listar");
        botProd.add(jMenuItem11);

        jMenuBar1.add(botProd);

        botSobre.setIcon(new javax.swing.ImageIcon("C:\\Users\\super\\OneDrive\\Documentos\\1FACULDADE\\Prog1\\FarmShow\\EstoqueFarmaShow\\src\\main\\java\\imagens\\help.png")); // NOI18N
        botSobre.setText("Sobre");
        botSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(botSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botSobreMouseClicked
        try {
        Desktop.getDesktop().browse(new URI("https://feevale.br/"));
        } 
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_botSobreMouseClicked

    private void botSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botSairMousePressed
        System.exit(0);
    }//GEN-LAST:event_botSairMousePressed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        TelaCadUser telaCadUser = new TelaCadUser();
        telaCadUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCadUser telaCadUser = new TelaCadUser();
        telaCadUser.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botArq;
    private javax.swing.JMenu botForne;
    private javax.swing.JMenu botProd;
    private javax.swing.JMenuItem botSair;
    private javax.swing.JMenu botSobre;
    private javax.swing.JMenu botUser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
